CRUD-6/CRUD6/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("movie/", views.movie),
    path("show/", views.show),
    path("edit/<int:mid>", views.edit),
    path("update/<int:mid>", views.update),
    path("delete/<int:mid>", views.delete),
]

CRUD-6/app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    mid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=50)
    date_released = models.DateField()
    def __str__(self):
        return self.title
    class Meta:
        db_table = 'Movie'

CRUD-6/app/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

CRUD-6/app/views.py
from django.shortcuts import render, redirect
from .forms import MovieForm
from .models import Movie
# Create your views here.
def home(request):
    return render(request, 'home.html')

def movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        try : 
            if form.is_valid():
                form.save()
                return redirect('/show')
        except: 
            pass
    else:
        form = MovieForm()
    return render(request, 'index.html', {'form': form})

def show(request):
    movies = Movie.objects.all()
    return render(request,'show.html', {'movies': movies})

def edit(request, mid):
    movie = Movie.objects.get(mid=mid)
    return render(request, 'edit.html', {'movie': movie})

def update(request, mid):
    movie = Movie.objects.get(mid=mid)
    form = MovieForm(request.POST, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html', {'movie': movie})

def delete(request, mid):
    movie = Movie.objects.get(mid=mid)
    movie.delete()
    return redirect('/show')

CRUD-6/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Movies App</title>
</head>
<body>
    <form action="/update/{{movie.mid}}" method="post" class="post-form">
        {% csrf_token %}
            <div class="container">
                <h2>Movie Management System</h2>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Update Movie Details : </h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Movie ID : </label>
                    <div class="col-sm-4">
                        <input type="hidden" name="mid" id="id_mid" value="{{ movie.mid }}" required maxlength="50"/> 
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Movie Title : </label>
                    <div class="col-sm-4">
                        <input type="text" name="title" id="id_title" value="{{ movie.title }}" required maxlength="50"/> 
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Movie Director : </label>
                    <div class="col-sm-4">
                        <input type="text" name="director" id="id_director" value="{{ movie.director }}" required maxlength="50"/> 
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Date Released : </label>
                    <div class="col-sm-4">
                        <input type="date" name="date_released" id="id_date_released" value="{{ movie.date_released }}" required/> 
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-warning">Save Changes</button>
                        <button type="reset" class="btn btn-dark">Reset</button>
                    </div>
                </div>
            </div>
    </form>
</body>
</html>

CRUD-6/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Movies App</title>
</head>
<body>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <h2>Movies App</h2>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Movie Details : </h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Movie ID : </label>
                <div class="col-sm-4">
                    {{ form.mid }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Movie Title : </label>
                <div class="col-sm-4">
                    {{ form.title }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Movie Director : </label>
                <div class="col-sm-4">
                    {{ form.director }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Date Released : </label>
                <div class="col-sm-4">
                    {{ form.date_released }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>

        </div>
    </form>
</body>
</html>

CRUD-6/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Movies App</title>
</head>
<body>
    <table class="table table-bordered table-striped table-sm table-dark">
        <thead class="thead-dark">
            <tr>
                <th>Movie ID</th>
                <th>Movie Title</th>
                <th>Movie Director</th>
                <th>Date Released</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% if not movies %}
                <tr align="center">
                    <td colspan="6">No Movie Record Found!!!</td>
                </tr>
                {% else %}
                {% for movie in movies %}
                <tr>
                    <td>{{ movie.mid }}</td>
                    <td>{{ movie.title }}</td>
                    <td>{{ movie.director }}</td>
                    <td>{{ movie.date_released }}</td>
                    <td>
                        <a href="/update/{{movie.mid}}" class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil">Edit Movie</span>
                        </a>&emsp; &emsp;
                        <a href="/delete/{{movie.mid}}" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash">Delete Movie</span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
    <center>
        <a href="/movie" class="btn btn-warning">Add New Movies</a>
    </center>
</body>
</html>