CRUD-3/CRUD3/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("book/", views.book),
    path("show/", views.show),
    path("edit/<int:bid>", views.edit),
    path("update/<int:bid>", views.update),
    path("delete/<int:bid>", views.delete),
]

CRUD-3/app/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    bid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    date_published = models.DateField()
    no_of_pages = models.PositiveSmallIntegerField()
    def __str__(self):
        return self.title

CRUD-3/app/forms.py
from django import forms
from .models import Book
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

CRUD-3/app/views.py
from django.shortcuts import render, redirect
from .forms import BookForm
from .models import Book
# Create your views here.
def home(request):
    return render(request, 'home.html')

def book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = BookForm()
    return render(request, 'index.html',{'form':form})

def show(request):
    books = Book.objects.all()
    return render(request, 'show.html',{'books':books})

def edit(request, bid):
    book = Book.objects.get(bid=bid)
    return render(request, 'edit.html',{'book':book})

def update(request, bid):
    book = Book.objects.get(bid=bid)
    form = BookForm(request.POST, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html',{'book':book})

def delete(request, bid):
    book = Book.objects.get(bid=bid)
    book.delete()
    return redirect('/show')

CRUD-3/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Book Information System</title>
</head>
<body>
    <form  method="post" class="post-form" action="/update/{{book.bid}}">
        {% csrf_token %}
        <div class="container">
            <center>
                <h2>Book Management System</h2>
            </center>
            <div class="form-group row">
                <label  class="col-sm-5 col-form-label"></label>
                <div class="col-sm-4">
                    <h2>Update Book Details : </h2>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ID : </label>
                <div class="col-sm-4">
                    <input type="text" name="bid" id="id_bid" value="{{ book.bid }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Title : </label>
                <div class="col-sm-4">
                    <input type="text" name="title" id="id_title" required max_length="50" value="{{ book.title }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Author : </label>
                <div class="col-sm-4">
                    <input type="text" name="author" id="id_author" required max_length="55" value="{{ book.author }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Published Date : </label>
                <div class="col-sm-4">
                    <input type="date" name="date_published" id="id_date_published" required  value="{{ book.date_published }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Total Pages : </label>
                <div class="col-sm-4">
                    <input type="number" name="no_of_pages" id="id_no_of_pages" required  value="{{ book.no_of_pages }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-5 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Update</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

CRUD-3/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Book Information System</title>
</head>
<body>
    <form  method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <center>
                <h2>Book Management System</h2>
            </center>
            <div class="form-group row">
                <label  class="col-sm-5 col-form-label"></label>
                <div class="col-sm-4">
                    <h2>Enter Book Details : </h2>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ID : </label>
                <div class="col-sm-4">{{ form.bid }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Title : </label>
                <div class="col-sm-4">{{ form.title }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Author : </label>
                <div class="col-sm-4">{{ form.author }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Published Date : </label>
                <div class="col-sm-4">{{ form.date_published }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Total Pages : </label>
                <div class="col-sm-4">{{ form.no_of_pages }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-5 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

CRUD-3/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Book Information System</title>
</head>
<body>
    <table class="table table-striped table-bordered table-sm table-dark">
        <thead class="thead-dark">
            <tr>
                <th>Book ID</th>
                <th>Book Title</th>
                <th>Book Author</th>
                <th>Date Published</th>
                <th>No of Pages</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% if not books %}
                <tr align="center">
                    <td colspan="6">No Book Records Found!!!</td>
                </tr>
                {% else %}
                {% for book in books %}
                    <tr>
                        <td>{{ book.bid }}</td>
                        <td>{{ book.title }}</td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.date_published }}</td>
                        <td>{{ book.no_of_pages }}</td>
                        <td>
                            <a href="/update/{{ book.bid }}" class="btn btn-primary">
                                <span class="glyphicon glyphicon-pencil">Edit</span>
                            </a>
                            <a href="/delete/{{ book.bid }}" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table><br><br>
   <center> 
        <a href="/book" class="btn btn-primary">Add New Record</a>    
    </center>
</body>
</html>