CRUD-4/CRUD4/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("order/", views.order),
    path("show/", views.show),
    path("edit/<int:oid>", views.edit),
    path("update/<int:oid>", views.update),
    path("delete/<int:oid>",views.delete),
]

CRUD-4/app/models.py
from django.db import models

# Create your models here.
class Order(models.Model):
    oid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=10)
    details = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'Order'

CRUD-4/app/forms.py
from django import forms
from .models import Order
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['oid', 'name', 'phone', 'details']

CRUD-4/app/views.py
from django.shortcuts import render,redirect
from .forms import OrderForm
from .models import Order
# Create your views here.
def home(request):
    return render(request, 'home.html')

def order(request):
    if request.method == "POST":
        form = OrderForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except :
            pass
    else:
        form = OrderForm()
    return render(request, 'index.html',{'form':form})
        
def show(request):
    orders = Order.objects.all()
    return render(request, 'show.html',{"orders":orders})

def edit(request, oid):
    order  = Order.objects.get(oid=oid)
    return render(request, 'edit.html',{"order":order})

def update(request, oid):
    order  = Order.objects.get(oid=oid)
    form = OrderForm(request.POST, instance=order)
    if form.is_valid():
            form.save()
            return redirect('/show')
    return render(request, 'edit.html',{"order":order})

def delete(request, oid):
    order = Order.objects.get(oid=oid)
    order.delete()
    return redirect('/show')

CRUD-4/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Order Management System</title>
</head>
<body>
    <form action="/update/{{order.oid}}" method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <h2>Update Order Details</h2>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details : </h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Order ID : </label>
                <div class="col-sm-4">
                    <input type="hidden" name="oid" id="id_oid" value="{{ order.oid }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Customer Name : </label>
                <div class="col-sm-4">
                    <input type="text" name="name" id="id_name" value="{{ order.name }}" required max_length="20"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Customer Contact No. : </label>
                <div class="col-sm-4">
                    <input type="number" name="phone" id="id_phone" value="{{ order.phone }}" required max_length="10"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Order Details : </label>
                <div class="col-sm-4">
                    <input type="text" name="details" id="id_details" value="{{ order.details }}" required max_length="100"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <button type="reset" class="btn btn-danger">Reset</button>
                </div>
            </div>

        </div>
    </form>
</body>
</html>

CRUD-4/app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Order Management System</title>
</head>
<body>
    <table border="1px solid black" align="center">
        <tr align="center">
            <th>Order Management System</th>
        </tr>
        <tr>
            <td>
                <center>
                    <img src="https://cdn.vectorstock.com/i/1000x1000/80/95/order-sign-logo-design-template-vector-31578095.webp" alt="order logo" width="40%">
                </center>
            </td>
        </tr>
        <tr>
            <td>
                <center>
                    <a href="/show" class="btn btn-dark">Show Orders</a>
                </center>
            </td>
        </tr>
    </table>
</body>
</html>

CRUD-4/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Order Management System</title>
    </head>
    <body>
        <form method="post" class="post-form">
            {% csrf_token %}
            <div class="container">
                <h2>Order Management System </h2>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-4">
                            <h3>Enter Order Details : </h3>
                        </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Order ID : </label>
                    <div class="col-sm-4">{{ form.oid }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Customer Name : </label>
                    <div class="col-sm-4">{{ form.name }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Customer Contact No. : </label>
                    <div class="col-sm-4">{{ form.phone }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Customer Order Details : </label>
                    <div class="col-sm-4">{{ form.details }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-5">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

CRUD-4/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Order Management System</title>
    </head>
    <body>
            <table class="table table-bordered table-stripped table-sm table-dark">
                <thead class="thead-dark">
                    <tr>
                        <th>Order ID</th>
                        <th>Customer Name</th>
                        <th>Customer Contact No.</th>
                        <th>Order Details</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% if not orders %}
                        <tr align="center">
                            <td colspan="5">No Orders!!!</td>
                        </tr>
                        {% else %}
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.oid}}</td>
                                <td>{{ order.name}}</td>
                                <td>{{ order.phone}}</td>
                                <td>{{ order.details}}</td>
                                <td>
                                    <a href="/update/{{ order.oid }}" class="btn btn-primary">
                                        <span class="glyphicon glyphicon-pencil">Edit Order</span>
                                    </a>&emsp; &emsp; 
                                    <a href="/delete/{{ order.oid }}" class="btn btn-danger">Delete Order</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
            <center>
                <a href="/order" class="btn btn-primary">Add New Order</a>
            </center>
    </body>
</html>