CRUD-1/project/project/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('emp/', views.emp),
    path('show/', views.show),
    path('edit/<int:Eid>', views.edit),
    path('update/<int:Eid>', views.update),
    path('delete/<int:Eid>', views.delete),
]

CRUD-1/project/app/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
  Eid  = models.CharField(primary_key=True,max_length=10)
  Ename = models.CharField(max_length=200)
  Eemail = models.EmailField()
  Econtact = models.CharField(max_length=15)
  class Meta:
    db_table = 'employee'
  def __str__(self):
    return self.Ename

CRUD-1/project/app/forms.py
from django import forms
from  .models import Employee

class EmployeeForm(forms.ModelForm):
  class Meta:
    model = Employee
    fields = '__all__'
    

CRUD-1/project/app/views.py
from django.shortcuts import render,redirect
from .forms import EmployeeForm
from .models import Employee

# Create your views here.
def home(request):
  return render(request, 'home.html')

def emp(request):
  if request.method == 'POST':
    form = EmployeeForm(request.POST)
    try:
         if form.is_valid():
          form.save()
          return redirect('/show')
    except:
        pass
  else:
      form = EmployeeForm()
  return render(request,'index.html',{'form':form})
  
def show(request):
  employees = Employee.objects.all()
  return render(request,'show.html',{ 'employees' : employees })

def edit(reuest,Eid):
  employee=Employee.objects.get(Eid=Eid)
  return render(reuest,'edit.html',{"employee":employee})

def update(request,Eid):
  employee = Employee.objects.get(Eid=Eid)
  form  = EmployeeForm(request.POST,instance=employee)
  if form.is_valid():
    form.save()
    return redirect('/show')
  return render(request,'edit.html',{"employee":employee})

def delete(request,Eid):
  employee = Employee.objects.get(Eid=Eid)
  employee.delete()
  return redirect("/show")


CRUD-1/project/app/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit</title>
  <link rel="stylesheet" href="{% static 'style.css' %}"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <form method="POST" class="post-form" action = '/update/{{employee.Eid}}'>
    {% csrf_token %}
    <div class="container">
      <br>
      <h2>Employee Information: </h2><br>
      <div class="from-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Update Details:</h3>
        </div>
      </div>

      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          <input type="text" name="Eid" id="id_Eid" required maxlength="20" value="{{ employee.Eid }}"/>
        </div>
      </div>

      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          <input type="text" name="Ename" id="id_Ename" required maxlength="100" value="{{ employee.Ename }}"/>
        </div>
      </div>

      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          <input type="email" name="Eemail" id="id_Eemail" required maxlength="254" value="{{ employee.Eemail }}"/>
        </div>
      </div>

      <div class="from-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          <input type="text" name="Econtact" id="id_Econtact" required maxlength="20" value="{{ employee.EContact }}"/>

        </div>
      </div>

      <div class="form-group row">  
        <label class="col-sm-3 col-form-label"></label>  
        <div class="col-sm-4">  
          <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>

    </div>
  </form>
</body>
</html>

CRUD-1/project/app/templates/home.html
<!DOCTYPE html>
<html>
<head>
<style>
a:link, a:visited {
  background-color: #f44336;
  color: white;
  padding: 14px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

a:hover, a:active {
  background-color: red;
}
</style>
</head>
<body>

<h2>HELLO, THIS IS A HOME PAGE</h2>

<p>Click Button To Show Employee Information:</p>
<a href="/show" target="_blank">CLICK HERE!!!</a>

</body>
</html>

CRUD-1/project/app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Index</title>
  <link rel="stylesheet" href="{% static 'style.css' %}"/> 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <form method="post" class=" post-form">
    {% csrf_token %}
    <div class="container">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">
          <h3>Enter Employee Details</h3>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          {{ form.Eid }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          {{ form.Ename }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{ form.Eemail }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          {{ form.Econtact }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>

  </form>
</body>
</html>

CRUD-1/project/app/templates/show.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Show</title>
  <link rel="stylesheet" href="{% static 'style.css' %}"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <table class= "table table-striped table-bordered table-sm">
    <thead class = "thead-dark">
      <tr>
        <th>Employee Id</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>

      </tr>
    </thead>
    <tbody>
      {% if not employees %}
      <tr align="center">
        <td colspan="5">No Employee Record Found!!!</td>
      </tr>
      {% else %}
        {% for employee in employees %}
          <tr>
            <td>{{employee.Eid}}</td>
            <td>{{employee.Ename}}</td>
            <td>{{employee.Eemail}}</td>
            <td>{{employee.Econtact}}</td>
            <td>
              <a href="/edit/{{ employee.Eid }}"><span class = "glyphicon glyphicon-pencil">Edit</span></a>
              <a href="/delete/{{ employee.Eid }}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      {% endif %}
    </tbody>
  </table>
  <br>
  <br>
  <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>